### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Steanky**
Another sizable merge to main

### CODE REVIEW

**Comment by Sternig** [comment]
hi

**Comment by Steanky** [comment]
hello

**Comment by Sternig** [comment]
most modifiers will not be done until next week right which will give me some time until i finish my exams and then can show you the modifier GUI stuff i came up with

**Comment by Sternig** [comment]
and do you know how im going to troll you? by making modifiers modifiable

**Comment by Steanky** [comment]
in that case, i won't work on the GUI stuff yet
and wdym by modifiable modifiers?

**Comment by Sternig** [comment]
making the modifier values modifiable

**Comment by Steanky** [comment]
like players being able to select, for example, specific mob health increase values for the mob health modifiers?

**Comment by Sternig** [comment]
you'd have a bar at the top or bottom of the GUI that lets you change the value however you want, like: [-10%] [-5%] [-1%] [DEFAULT (reset to default)] [+1%] [+5%] [+10%]

**Comment by Steanky** [comment]
i don't think this is worth implementing, most modifiers aren't going to be based on a single numerical value that can be changed to whatever the player wants

**Comment by Steanky** [comment]
its really just mob attribute modifiers that this works with
also it would ruin the ability to have leaderboards for a specific set of modifiers

**Comment by Sternig** [comment]
fair i guess, i just thought it'd be nice for people who don't really want to go with +50% hp for all mobs right away

**Comment by Sternig** [comment]
IMG_20220520_144716
gigabird2

**Comment by Steanky** [comment]
i agree, we can have separate modifiers for different increments of HP increase
so like +25% health, +50%, +100%

**Pull request merged**
