### PR TITLE
made testing more efficient

### PR DESCRIPTION
**Pull request by parkab**

### CODE REVIEW

**Comment by parkab** [comment]
i worked very hard on these tests

**Comment by Steanky** [comment]
No justification given for removing these tests.

**Comment by parkab** [comment]
tests are inefficient and a waste of time and space, I learned this in my software engineering class

**Comment by Steanky** [comment]
well, my cybersecurity course has taught me that the internet is inefficient and a waste of time and space, we should share code using written letters rather than git repositories

**Comment by parkab** [comment]
i'd rather communicate using a book and quill in gau

**Pull request closed without merging**
